package it.cs.unicam.app_Comune.InformazioneTerritoriale;
/**
 * Enumerazione che rappresenta i tipi di struttura
 */
public enum TipoStruttura {
    AEROPORTO, ALBERGO, ALTRO, ATTRAZIONE_TURISTICA, AUTOVELOX, CAMPO_BASEBALL,
    CAMPO_BASKET, CAMPO_BOCCE, CAMPO_BOCCETTE, CAMPO_BOWLING, CAMPO_CALCIO,
    CAMPO_CRICKET, CAMPO_GOLF, CAMPO_HOCKEY, CAMPO_LACROSSE,
    CAMPO_PALLAMANO, CAMPO_PALLAVOLO, CAMPO_RUGBY, CAMPO_SOFTBALL, CAMPO_SQUASH,
    CAMPO_TENNIS, CASCATA, CASERMA_CARABINIERI, CASERMA_POLIZIA,
    CATENE_MONTUOSE, CENTRO_COMMERCIALE, CHIESA, CINEMA, COMUNE, FARMACIA,
    FERMATA_BUS, FERMATA_METRO, FERMATA_TRAM, FERMATA_TRENO,
    MONUMENTO, MUSEO, NEGOZIO, OSPEDALE, PALESTRA, PARCHEGGIO,
    PARCO, PISCINA, PIZZERIA, RISTORANTE, SCUOLA, STADIO, STATUA, TEATRO,
    UNIVERSITA, ZONA_AGRICOLA, ZONA_ARTIGIANALE, ZONA_BALNEARE, ZONA_BOSCOSA, ZONA_COLLINARE,
    ZONA_COMMERCIALE, ZONA_FLUVIALE, ZONA_INDUSTRIALE, ZONA_LACUSTRE, ZONA_MARINA, ZONA_MONTANA,
    ZONA_RESIDENZIALE, ZONA_RICREATIVA, ZONA_SPORTIVA, ZONA_TURISTICA, ZONA_VERDE,
    ZOO
}
