package it.cs.unicam.app_Comune.InformazioneTerritoriale;

public enum TipoItinerario {
    ESCURSIONE, VIAGGIO_STRADALE, CROCIERA, VOLO, TOUR_GUIDATO, CICLOTURISMO, TREKKING, PELLEGRINAGGIO,
    ITINERARIO_CULTURALE, ITINERARIO_ENOGASTRONOMICO, ITINERARIO_NATURALE, ITINERARIO_RELIGIOSO, ITINERARIO_DIVERTIMENTO,
    ITINERARIO_DIDATTICO, ITINERARIO_ALTRO
}
